version: '3.8'

services:
  backend:
    image: maxifuentes2/entrega-final:latest
    container_name: api-mascotas
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/entrega-final
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: db-mascotas
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: